In [4]:
import numpy as np


In [3]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 1.8 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/12.9 MB 1.7 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.9 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.9 MB 1.9 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.9 MB 1.9 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.9 MB 2.0 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.9 MB 2.0 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.9 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.9 MB 1.8 MB/s eta 0:00:06
   ------------ --------------------------- 3.9/12.9 MB 1.8 MB/s eta 0:00:06
   -------------- ------------------------- 4.7/12.9 MB 1.9 MB/s eta 0:00:05
   ----------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#creation of 1D array:

arr=np.array([20,30,40,50,80])  #5 rows
print(arr)

[20 30 40 50 80]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [8]:
new_2=np.array((2,3,4,55))
print(new_2)

[ 2  3  4 55]


In [9]:
new_dict=np.array( {32,2,9,50})
print(new_dict)

{32, 9, 2, 50}


In [10]:
type(new_dict)

numpy.ndarray

In [11]:
new_dict.ndim

0

In [12]:
arr.ndim

1

In [14]:
arr.shape

(5,)

In [13]:
two_dim=np.array( [ [22,23],[43,8], [50,49]])
print(two_dim)

[[22 23]
 [43  8]
 [50 49]]


In [15]:
two_dim.shape

(3, 2)

In [16]:
two_dim.ndim

2

What is difference between numpy array and Python list?

In [17]:
print(arr)

[20 30 40 50 80]


In [18]:
listl=[3,2,5,6]
listl

[3, 2, 5, 6]

In [19]:
list_1=[20,30,40]
list_2=[10,20,30]
#add

lis=[]
for i,j in zip(list_1,list_2):
    lis.append( i+j)
print(lis)

[30, 50, 70]


In [21]:
list_1+ list_2  #not addition but concatenation

[20, 30, 40, 10, 20, 30]

In [22]:
ar_1= np.array([20,30,40])
ar_2= np.array( [10,20,30])
#add
ar_1+ar_2

array([30, 50, 70])

In [23]:
ar_1*ar_2

array([ 200,  600, 1200])

List: consists of any type of data  but reshaping & resizing is not allowed as array
array : same datatype

Numpy arrays are faster as compared to that of list.
less time & space

In [24]:
#indexing
ar_1[2]

np.int64(40)

In [25]:
ar_2[-1]

np.int64(30)

In [26]:
two_dim[2][3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [29]:
two_dim[1][1]    #row[1],in 1row --col:1

np.int64(8)

In [30]:
two_dim[0][1]

np.int64(23)

In [31]:
two_dim[0][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [32]:
two_dim[0:1]

array([[22, 23]])

In [33]:
#Slicing
two_dim[0: ,1:]

array([[23],
       [ 8],
       [49]])

In [34]:
dim_2rr=np.array( [[20,30,40],[30,40,50],[60,30,70]])
print(dim_2rr)

[[20 30 40]
 [30 40 50]
 [60 30 70]]


In [35]:
dim_2rr[ 1: ,1:]

array([[40, 50],
       [30, 70]])

In [36]:
dim_2rr[0:, 1:]

array([[30, 40],
       [40, 50],
       [30, 70]])

In [37]:
dim_2rr[0:2, 0:2]

array([[20, 30],
       [30, 40]])

In [38]:
dim_2rr[0:3, 0:3]

array([[20, 30, 40],
       [30, 40, 50],
       [60, 30, 70]])

In [40]:
dim_2rr[0:2, ::2]   #jump=2

array([[20, 40],
       [30, 50]])

In [41]:
dim_2rr[::2, :]

array([[20, 30, 40],
       [60, 30, 70]])