Creation of different types of array

In [1]:
import numpy as np

In [2]:
num_f=np.array( [2,3,4,5],dtype="float")
print(num_f)

[2. 3. 4. 5.]


In [3]:
num_com=np.array( [1,2,3,4],dtype="complex")
print(num_com)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [4]:
#create with arrange method

#print table
list_r=[]
for i in range(2,21,2):
    list_r.append(i)
print(list_r)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
x=np.arange(2,21,2)
print(x)

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
np.arange(20,39,3).reshape(7,1)

array([[20],
       [23],
       [26],
       [29],
       [32],
       [35],
       [38]])

In [10]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
np.arange(1,8).reshape(2,-1)

ValueError: cannot reshape array of size 7 into shape (2,newaxis)

In [13]:
np.arange(1,7).reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.arange(1,7).reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.arange(1,7).reshape(-1,6)

array([[1, 2, 3, 4, 5, 6]])

#Array of zeros

In [20]:
np.zeros( (10), dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros( (10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.ones((9))

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((8,8), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
#Array of random elements:
np.array( [[20,30,40,50]])

array([[20, 30, 40, 50]])

In [25]:
np.random.random(8,5)

TypeError: random() takes at most 1 positional argument (2 given)

In [38]:
np.random.random((8,5))

array([[0.58268489, 0.02555094, 0.66220202, 0.38752343, 0.4970738 ],
       [0.41490584, 0.3508719 , 0.55097791, 0.97291069, 0.11277622],
       [0.31325853, 0.04179771, 0.73839976, 0.65751239, 0.21463575],
       [0.41675344, 0.64384193, 0.66148133, 0.17047713, 0.88165224],
       [0.77800816, 0.13395421, 0.86891663, 0.74877788, 0.79858565],
       [0.54334523, 0.22083792, 0.91845865, 0.59208458, 0.34623791],
       [0.26377853, 0.91391548, 0.41973546, 0.54019152, 0.60844216],
       [0.82624983, 0.62356318, 0.17671216, 0.59125735, 0.48926617]])

In [53]:
rt=np.random.randint(5,20,(4,7))

In [54]:
rt

array([[ 8, 11, 16,  6,  9, 15, 16],
       [ 5, 19, 13, 15, 10, 17,  9],
       [16, 19,  7, 14, 12,  6, 14],
       [ 7,  6, 16, 19,  5, 12,  6]], dtype=int32)

In [55]:
rt

array([[ 8, 11, 16,  6,  9, 15, 16],
       [ 5, 19, 13, 15, 10, 17,  9],
       [16, 19,  7, 14, 12,  6, 14],
       [ 7,  6, 16, 19,  5, 12,  6]], dtype=int32)

In [46]:
np.random.seed(2)  #any number
x=np.random.random((8,5))

In [45]:
x

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548],
       [0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997],
       [0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629],
       [0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672],
       [0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235]])

In [50]:
n=np.random.randint(2,20,(3,4))
print(n)

[[11  7  8  8]
 [ 3  6 10 19]
 [ 8  7  3 13]]


In [49]:
n

array([[4, 4, 2, 2],
       [4, 4, 2, 2],
       [4, 4, 2, 4]], dtype=int32)

In [51]:
n

array([[11,  7,  8,  8],
       [ 3,  6, 10, 19],
       [ 8,  7,  3, 13]], dtype=int32)