In [1]:
import numpy as np

#Array attributes:

In [2]:
dim1=np.arange(8)

In [3]:
dim1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
dim2=np.arange(12,dtype="float").reshape(3,4)
dim3=np.arange(8).reshape(2,2,2)

In [6]:
dim2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [7]:
dim3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
dim1.size

8

In [9]:
dim2.size

12

In [10]:
dim1.shape

(8,)

In [11]:
#changing the datatype of pre-existing array
dim2=dim2.astype(np.int32)

In [12]:
dim2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [13]:
dim2> 8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [14]:
dim2*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]], dtype=int32)

In [16]:
d4=np.arange(12,24).reshape(3,4)
d4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
print(dim2+d4)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


#Array functions:

In [20]:
from numpy._core.fromnumeric import prod
print( np.prod(dim2))

0


In [21]:
np.prod(d4)

np.int64(647647525324800)

In [22]:
dim2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [23]:
np.min(dim2)

np.int32(0)

In [24]:
print(np.min(dim2))

0


In [25]:
print(np.max(dim2))

11


In [26]:
print( np.sum(dim2))

66


In [27]:
print(np.mean(dim2))

5.5


In [28]:
#finding mean across the rows
print( np.mean(dim2, axis=1))

[1.5 5.5 9.5]


In [30]:
print( np.mean(dim2, axis=0))  #col: axis=0, row:1

[4. 5. 6. 7.]


#std: a measure of how much variation exists from the mean of a data

In [31]:
print( np.std(dim2))

3.452052529534663


In [32]:
print ( np.var(dim2))

11.916666666666666


#dot product of two [],[]:

In [33]:
dim2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [34]:
d4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
dot_prod=np.dot(dim2,d5)

In [36]:
d5=np.arange(12,24).reshape(4,3)
d5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [38]:
dot_prod

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [39]:
#how iterate over matrix

for i in dot_prod:
    print(i)

[114 120 126]
[378 400 422]
[642 680 718]


In [40]:
for i in dot_prod:
    for j in i:
        print(j)

114
120
126
378
400
422
642
680
718


In [41]:
for i in np.nditer(dot_prod):
    print(i)

114
120
126
378
400
422
642
680
718


#Conversion of 2D in one Dimension:

In [42]:
dot_prod.ravel()

array([114, 120, 126, 378, 400, 422, 642, 680, 718])

In [43]:
#stacking & splitting